// <auto-generated />
using System;
using ManageBookInformation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageBookInformation.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231026044443_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManageBookInformation.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPages")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("568f0ec0-f4b0-4eee-be3f-f8966bf248b2"),
                            Author = "Sample Author 1",
                            ISBN = "1234567890",
                            NumberOfPages = 200,
                            PublicationYear = 2023,
                            Title = "Sample Book 1"
                        },
                        new
                        {
                            Id = new Guid("169eaa41-0d5c-415b-9c32-4f7bb692460b"),
                            Author = "Sample Author 2",
                            ISBN = "0987654321",
                            NumberOfPages = 300,
                            PublicationYear = 2024,
                            Title = "Sample Book 2"
                        },
                        new
                        {
                            Id = new Guid("9bf341fc-2727-475c-a226-1135fed3c713"),
                            Author = "Sample Author 3",
                            ISBN = "1212121212",
                            NumberOfPages = 400,
                            PublicationYear = 2025,
                            Title = "Sample Book 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
